global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'netops-platform'
    environment: 'dev'
 
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
 
rule_files:
  - /etc/prometheus/rules/*.yml
 
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
 
  # Node Exporter (Docker host)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
 
  # Django application metrics
  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']
    metrics_path: '/metrics'
 
  # ── SNMP: Sofia Site ──────────────────────────────────────────────────────
  - job_name: cisco_switches
    metrics_path: /snmp
    params:
      module: [cisco_switch]
      auth: [cisco_v2]
    static_configs:
      - targets:
          - 192.168.1.100
          - 192.168.1.101
          - 192.168.1.102
          - 192.168.1.109
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter1:9116
 
 
 
  # - job_name: 'snmp_sofia_fw_primary'
  #   static_configs:
  #     - targets: ['192.168.100.10']
  #   metrics_path: /snmp
  #   params:
  #     module: [cisco_switch]
  #     auth:   [public_v2]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp_exporter:9116
  #     - target_label: site
  #       replacement: sofia
  #     - target_label: role
  #       replacement: firewall_primary
 
  # - job_name: 'snmp_sofia_fw_secondary'
  #   static_configs:
  #     - targets: ['192.168.100.11']
  #   metrics_path: /snmp
  #   params:
  #     module: [cisco_switch]
  #     auth:   [public_v2]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp_exporter:9116
  #     - target_label: site
  #       replacement: sofia
  #     - target_label: role
  #       replacement: firewall_secondary
 
  - job_name: 'snmp_sofia_router'
    static_configs:
      - targets: ['192.168.1.100']
    metrics_path: /snmp
    params:
      module: [cisco_switch]
      auth:   [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter1:9116
      - target_label: site
        replacement: sofia
      - target_label: role
        replacement: router
 
  # # ── SNMP: Burgas Site ─────────────────────────────────────────────────────
  # - job_name: 'snmp_burgas_fw_primary'
  #   static_configs:
  #     - targets: ['192.168.100.20']
  #   metrics_path: /snmp
  #   params:
  #     module: [cisco_switch]
  #     auth:   [public_v2]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp_exporter:9116
  #     - target_label: site
  #       replacement: burgas
  #     - target_label: role
  #       replacement: firewall_primary
 
  # - job_name: 'snmp_burgas_fw_secondary'
  #   static_configs:
  #     - targets: ['192.168.100.21']
  #   metrics_path: /snmp
  #   params:
  #     module: [cisco_switch]
  #     auth:   [public_v2]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp_exporter:9116
  #     - target_label: site
  #       replacement: burgas
  #     - target_label: role
  #       replacement: firewall_secondary
 
  # - job_name: 'snmp_burgas_router'
  #   static_configs:
  #     - targets: ['192.168.100.22']
  #   metrics_path: /snmp
  #   params:
  #     module: [cisco_switch]
  #     auth:   [public_v2]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp_exporter:9116
  #     - target_label: site
  #       replacement: burgas
  #     - target_label: role
  #       replacement: router
 
  # # ── SNMP: Plovdiv Site ────────────────────────────────────────────────────
  # - job_name: 'snmp_plovdiv_fw_primary'
  #   static_configs:
  #     - targets: ['192.168.100.30']
  #   metrics_path: /snmp
  #   params:
  #     module: [cisco_switch]
  #     auth:   [public_v2]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp_exporter:9116
  #     - target_label: site
  #       replacement: plovdiv
  #     - target_label: role
  #       replacement: firewall_primary
 
  # - job_name: 'snmp_plovdiv_fw_secondary'
  #   static_configs:
  #     - targets: ['192.168.100.31']
  #   metrics_path: /snmp
  #   params:
  #     module: [cisco_switch]
  #     auth:   [public_v2]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp_exporter:9116
  #     - target_label: site
  #       replacement: plovdiv
  #     - target_label: role
  #       replacement: firewall_secondary
 
  # - job_name: 'snmp_plovdiv_router'
  #   static_configs:
  #     - targets: ['192.168.100.32']
  #   metrics_path: /snmp
  #   params:
  #     module: [cisco_switch]
  #     auth:   [public_v2]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp_exporter:9116
  #     - target_label: site
  #       replacement: plovdiv
  #     - target_label: role
  #       replacement: router