[cisco_devices]
R1          ansible_host=192.168.100.1  device_type=router
FW          ansible_host=192.168.100.2  device_type=firewall
Core-SW     ansible_host=192.168.100.10 device_type=switch
SW1         ansible_host=192.168.100.11 device_type=switch
SW2         ansible_host=192.168.100.12 device_type=switch

[cisco_devices:vars]
ansible_user=admin
ansible_password={{ lookup('env', 'DEVICE_PASSWORD') }}
ansible_network_os=ios
ansible_connection=network_cli
ansible_become=true
ansible_become_method=enable
